DROP INDEX Bibrecs.Indx;

DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON

SELECT title FROM Bibrecs WHERE title LIKE '%Πληροφορική%'
ORDER BY title

SET STATISTICS TIME OFF

DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON

SELECT title, material FROM Bibrecs WHERE title = 'Economics'
ORDER BY title

SET STATISTICS TIME OFF

DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON

SELECT title, material FROM Bibrecs WHERE title LIKE 'Economics%'
ORDER BY title

SET STATISTICS TIME OFF


CREATE INDEX Indx ON Bibrecs(title);

DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON

SELECT title FROM Bibrecs WHERE title LIKE '%Πληροφορική%'
ORDER BY title

SET STATISTICS TIME OFF

DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON

SELECT title, material FROM Bibrecs WHERE title = 'Economics'
ORDER BY title

SET STATISTICS TIME OFF

DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON

SELECT title, material FROM Bibrecs WHERE title LIKE 'Economics%'
ORDER BY title

SET STATISTICS TIME OFF